# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .metric_name import MetricName
from .metric_snapshot import MetricSnapshot


class MetricQuery(UniversalBaseModel):
    """
    A request for a single metric.
    """

    metric: MetricName
    snapshot: typing.Optional[MetricSnapshot] = pydantic.Field(default=None)
    """
    Which snapshot to read the metric from. Defaults to `today`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
