# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .export_date_too_early_error import ExportDateTooEarlyError
    from .export_disabled_error import ExportDisabledError
    from .export_files_unavailable_error import ExportFilesUnavailableError
    from .export_not_yet_available_error import ExportNotYetAvailableError
    from .missing_daily_incremental_export_file_error import MissingDailyIncrementalExportFileError
    from .unsupported_export_window_error import UnsupportedExportWindowError
_dynamic_imports: typing.Dict[str, str] = {
    "ExportDateTooEarlyError": ".export_date_too_early_error",
    "ExportDisabledError": ".export_disabled_error",
    "ExportFilesUnavailableError": ".export_files_unavailable_error",
    "ExportNotYetAvailableError": ".export_not_yet_available_error",
    "MissingDailyIncrementalExportFileError": ".missing_daily_incremental_export_file_error",
    "UnsupportedExportWindowError": ".unsupported_export_window_error",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ExportDateTooEarlyError",
    "ExportDisabledError",
    "ExportFilesUnavailableError",
    "ExportNotYetAvailableError",
    "MissingDailyIncrementalExportFileError",
    "UnsupportedExportWindowError",
]
