# This file was auto-generated by Fern from our API Definition.

import typing

from ........core import enum

T_Result = typing.TypeVar("T_Result")


class AdvancedDirective(enum.StrEnum):
    NONE = "NONE"
    DURABLE_POWER_OF_ATTORNEY = "DURABLE_POWER_OF_ATTORNEY"
    LIVING_WILL = "LIVING_WILL"
    DO_NOT_RESUSCITATE = "DO_NOT_RESUSCITATE"
    STANDARD_PRECAUTIONS = "STANDARD_PRECAUTIONS"
    FALL_RISK = "FALL_RISK"
    _UNKNOWN = "__ADVANCEDDIRECTIVE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "AdvancedDirective":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        none: typing.Callable[[], T_Result],
        durable_power_of_attorney: typing.Callable[[], T_Result],
        living_will: typing.Callable[[], T_Result],
        do_not_resuscitate: typing.Callable[[], T_Result],
        standard_precautions: typing.Callable[[], T_Result],
        fall_risk: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is AdvancedDirective.NONE:
            return none()
        if self is AdvancedDirective.DURABLE_POWER_OF_ATTORNEY:
            return durable_power_of_attorney()
        if self is AdvancedDirective.LIVING_WILL:
            return living_will()
        if self is AdvancedDirective.DO_NOT_RESUSCITATE:
            return do_not_resuscitate()
        if self is AdvancedDirective.STANDARD_PRECAUTIONS:
            return standard_precautions()
        if self is AdvancedDirective.FALL_RISK:
            return fall_risk()
        return _unknown_member(self._value_)
