# This file was auto-generated by Fern from our API Definition.

import typing

DenialReasonContent = typing.Union[
    typing.Literal[
        "Authorization Required",
        "Referral Required",
        "Medical Records Requested",
        "Timely Filing",
        "Duplicate Claim",
        "Incorrect Place of Service",
        "Incorrect Patient Gender",
        "Bundled",
        "Exceeded Billable Time",
        "Invalid Provider Information",
        "Invalid Diagnosis Code",
        "Incorrect Procedure Code",
        "Invalid Modifier",
        "Missing NDC Code",
        "Invalid Insurance Data",
        "No Active Coverage",
        "Coordination of Benefits",
        "Incorrect Payer",
        "Credentialing",
        "No Effective Contract",
        "Missing W-9",
        "Missing Contract Linkage",
        "Non-Covered Benefit",
        "Experimental Procedure",
        "Not Medically Necessary",
        "Info Requested from Provider",
        "Info Requested from Patient",
        "Billing Error",
        "Unknown",
        "Max Benefit Reached",
    ],
    typing.Any,
]
