# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ........core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....common.types.user_id import UserId
from .insurance_discovery_status import InsuranceDiscoveryStatus


class InsuranceDiscoveryCheckMetadata(UniversalBaseModel):
    check_id: str
    status: InsuranceDiscoveryStatus
    initiated_by: UserId
    initiated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
