# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ......core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_action_execution_method import TaskActionExecutionMethod
from .task_action_type import TaskActionType


class TaskAction(UniversalBaseModel):
    display_name: str
    execution_method: TaskActionExecutionMethod
    type: TaskActionType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
