# This file was auto-generated by Fern from our API Definition.

import typing

from ......core.api_error import ApiError
from ..types.m_2_m_user_failed_to_create_error import M2MUserFailedToCreateError


class M2MUserFailedToCreateHttpError(ApiError):
    def __init__(self, body: M2MUserFailedToCreateError, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=500, headers=headers, body=body)
