# This file was auto-generated by Fern from our API Definition.

from ......core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .....commons.types.source_of_payment_code import SourceOfPaymentCode
from .....commons.types.insurance_type_code import InsuranceTypeCode
from ......core.pydantic_utilities import IS_PYDANTIC_V2


class InsuranceCardBase(UniversalBaseModel):
    group_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Box 11 on the CMS-1500 claim form.
    """

    plan_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Box 11c on the CMS-1500 claim form.
    """

    plan_type: typing.Optional[SourceOfPaymentCode] = None
    insurance_type: typing.Optional[InsuranceTypeCode] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
