# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ......core.datetime_utils import serialize_datetime
from .....commons.types.service_line_id import ServiceLineId
from .claim_adjustment_reason_code import ClaimAdjustmentReasonCode
from .service_line_adjudication_create import ServiceLineAdjudicationCreate


class ClaimAdjudicationCreate(pydantic.BaseModel):
    insurance_allowed_amount_cents: typing.Optional[int]
    insurance_paid_amount_cents: typing.Optional[int]
    service_lines: typing.Dict[ServiceLineId, ServiceLineAdjudicationCreate]
    carcs: typing.List[ClaimAdjustmentReasonCode]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
