# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic

from .....commons.types.regions import Regions


class RegionsUpdate_Set(pydantic.BaseModel):
    value: Regions
    type: typing.Literal["set"] = "set"

    class Config:
        frozen = True
        smart_union = True


RegionsUpdate = typing.Union[RegionsUpdate_Set]
