# This file was auto-generated by Fern from our API Definition.

import typing

from ......core import enum

T_Result = typing.TypeVar("T_Result")


class UuidSetMatchMode(enum.StrEnum):
    IN = "in"
    NOT_IN = "not_in"
    _UNKNOWN = "__UUIDSETMATCHMODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "UuidSetMatchMode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        in_: typing.Callable[[], T_Result],
        not_in: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is UuidSetMatchMode.IN:
            return in_()
        if self is UuidSetMatchMode.NOT_IN:
            return not_in()
        return _unknown_member(self._value_)
