# This file was auto-generated by Fern from our API Definition.

from ........core.pydantic_utilities import UniversalBaseModel
from .....common.types.patient_id import PatientId
import typing
from ........core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PatientAssociation(UniversalBaseModel):
    """
    An association to a Patient.
    """

    id: PatientId
    notes: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
