# This file was auto-generated by Fern from our API Definition.

import typing

from ........core import enum

T_Result = typing.TypeVar("T_Result")


class NoteType(enum.StrEnum):
    """
    Distinguishes what a note is about. `GENERAL` = a plain patient note; `ELIGIBILITY` = a note regarding the patient's eligibility.
    """

    GENERAL = "GENERAL"
    ELIGIBILITY = "ELIGIBILITY"
    _UNKNOWN = "__NOTETYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "NoteType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        general: typing.Callable[[], T_Result],
        eligibility: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is NoteType.GENERAL:
            return general()
        if self is NoteType.ELIGIBILITY:
            return eligibility()
        return _unknown_member(self._value_)
