# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ChargeCaptureClaimCreationSortField(str, enum.Enum):
    CREATED_AT = "created_at"
    _UNKNOWN = "__CHARGECAPTURECLAIMCREATIONSORTFIELD_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ChargeCaptureClaimCreationSortField":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self, created_at: typing.Callable[[], T_Result], _unknown_member: typing.Callable[[str], T_Result]
    ) -> T_Result:
        if self is ChargeCaptureClaimCreationSortField.CREATED_AT:
            return created_at()
        return _unknown_member(self._value_)
